### ISSUE TITLE
No-compile development experience.

### ISSUE THREAD

**Issue by paulvanbladel** [DanWahlin/ES6-Modules-Starter#4]
I'm pretty new to javascript (well... relatively) but have a stronger background in .Net.
What I considered as appealing in my early javascript days, was that you could take a bunch of html and .js files and just run it by itself, no compilation or whatsoever required.
Today, this experience is gone, grunt/gulp and transpilers took a first citizen place. 
I think it's a pity that part of the simplicity of the javascript development time experience disappeared as such.  Especially, since one can observe that with Roslyn, .Net is going the opposite direction (roslyn compiles on the fly as you know). Note, I'm completely happy with taskrunners for minification, deployment, packaging, you name it.

Fortunately, there is also the option to apply in-browser-transpilation.
It could maybe worth including this also in the sample, together with type-script compilation and type-script in-browser compiliation ?
I understand that in browser compilation is only suitable for development time.

**Comment by johnpapa** [comment]
im against in browser compiling because it sends a message to the new dev that its ok.

but yes, for advanced devs, go for it.

**Comment by paulvanbladel** [comment]
Good point John. Thanks.
